# #
# # 1. what is django? main bultin fuctionality provided by djang?
# # Django is a high-level, open-source framework that helps developers build secure, scalable, and maintainable web applications quickly and efficiently.
# # It follows the Model–Template–View (MTV) architecture
# # features are
# # authentication
# # form handling
# # template engine
# # db connections
# # admin panel
# # url to view mapping
# # static file configu.
# #
# # 2.MVT Architecture of django(url to flow include)
#
# # Model-View-Template architecture, otherwise known as MVT, is a software design pattern within Django that utilizes:
# #
# # Models to handle data logic and structure of your database
# # Views to handle  logic part of the applications
# # Templates to handle the layout and structure of the user facing application
# #
# # flow==
# # 1. User requests a URL -2. URL matches a pattern in urls.py 3.-URL dispatcher sends the request to the view function.--4. View interacts with Model---4. View sends data to Template---5.Template renders HTML
# #
#
#
# # 3.orm feature?
# #
# # A Django ORM query is a Python-based Object-Relational Mapper (ORM) API
# # that allows you to interact with your database using Python code instead of writing raw SQLObject–Relational Mapping
# # (optional)
# # 1. Database Abstraction
# # 2. Model-Based Database Structure
# # 4. Field Lookups
# # 5.Relationships Handling (ForeignKey, ManyToMany, OneToOne)
#
#
# # 222222222222222222222222222222222222222222222222222222222222222222222222222222
#
#
# 1.What is the purpose of Django migrations?
#
# Django migrations are a version control system for your database schema,
# designed to automatically propagate changes made to your Django models (in Python code) into the actual database structure
#
# it involves two main commands:
# python manage.py makemigrations: This command scans your models for changes and
# creates a new Python migration file that records the corresponding modifications.
#
# python manage.py migrate: This command applies the pending migrations to the database,
# Django keeps track of which migrations have been applied in a special database table called django_migrations.
#
# 2.How does Django handle user authentication?
#
# Django authentication system handles both authentication and authorization.
# authentication verifies identity of user , and authorization determines what an authenticated user is allowed to do.
#
# it done through (django.contrib.auth) that manages users, groups, permissions, and cookie-based sessions
#
# Developers interact with the authentication system using functions:
#
# authenticate(): Takes credentials (e.g., username and password) and checks them with db data. It returns a User object if the credentials are valid, or None otherwise.
# login(): Allow authenticated user to get in the current session.
# logout(): Cleans out the current session data
# login_required decorator/mixin: it restrict  an unauthenticated user to access a protected view, they are redirected to the login page
#
#  3.Explain the role of Django admin.
#
# The Django admin is a built-in, automatically generated web interface.
# it have dashboard for managing an application's data and internal operations
# CRUD
# Operations: It provides ready - to - use interface to Create, Read, Update, and Delete(CRUD) records
# for any registered models in the database without writing additional views or backend code.
from wsgiref.util import request_uri

# 33333333333333333333333333333333333333333333333333333333333
#
# # 1.what do you mean by csrf_token
#  4jery
# A CSRF token (Cross-Site Request Forgery token) is a unique, secret, and unpredictable value generated by a web application
# to protect against CSRF attacks. It acts as a security measure , ensure that incoming requests are comes from user ratherthan attackers site

# In a CSRF attack, an attacker crafts a  web page that contains a hidden form or JavaScript code which sends a request to website
# where the user is currently logged in. Because the browser automatically includes the users session cookies with the request,
# website treats this request as genuine and performs the unintended action

# when uses csrf_token
# When the server sends a form to the client, it includes a unique CSRF token, often in a hidden form field or an HTTP header.
# The server also stores this token (or a hash of it) in the user's session data on the server side.
# Validation: When the user submits the form, the browser sends the token back to the server.
# The server-side application then compares the received token with the one stored in the user's session.


# # 2.Explain Q object in Django
# The Q object in Django is a powerful tool used to encapsulate SQL expressions,
# The Q object allowing developers to build complex database queries that use  AND, OR, and NOT logical operators.
# By default, keyword arguments in a filter() call are joined by AND conditions,
# but Q objects provide the flexibility to override this behavior and create more intricate logic.


# # 3.What is the role of middleware in django

# In Django, middleware is a framework of hooks that allows developers to intercept, modify
# , or enhance HTTP requests and responses in  the application's processing cycle#
purpose of middleware is,..to processing the request before reaches in view
                            to proccessing the responds before reaches in browser
                            used to handle and modify response and request
                            is used in authentication,security and in session

#Request Pre-processing
# Response Post-processing:

#                                revision4

# What are context processors in Django and how are they used?
Context processors offer a clean and efficient way to handle repetitive data requirements across your application
They are primarily used to inject common, necessary data into every template without the adding of that data in every view function
Reduced Redundancy will achieve through this
# What is Jinja templating?
Jinja is a fast, expressive, and extensible template engine for the Python programming language. It is used to generate
dynamic content by combining static text files (templates) with dynamic data

{{ ... }}	Expressions to print output	Hello, {{ name }}!
{% ... %}	Statements for control flow

# What is the difference between function-based views and class-based views in Django?
# Function-Based Views (FBVs) are simple Python functions that receive a request and return a response, offering explicit control over code flow. Class-Based Views (CBVs) are Python classes that use
# object-oriented principles like inheritance and mixins, promoting code reuse and better structure for complex applications.
# Feature 	Function-Based Views (FBVs)	Class-Based Views (CBVs)
# Implementation	Implemented as a Python function that accepts request as an argument.	Implemented as a Python class that inherits from django.views.View or a generic view.
# HTTP Methods	Handled using conditional branching (e.g., if request.method == 'POST') within a single function.	Each HTTP method (e.g., get(), post()) is handled by a separate method within the class.
# Code Reusability	Limited; often leads to repetitive "boilerplate" code for common tasks like form handling.	Highly reusable through inheritance and mixins, which follow the DRY (Don't Repeat Yourself) principle.
# Code Flow	Explicit and easy to trace, which is beginner-friendly.	More implicit due to abstraction, inheritance, and the as_view() and dispatch() methods, potentially making debugging harder for beginners.


#                            revision5

#  What databases are supported by Django?5
# Django officially supports the following relational databases:
# PostgreSQL: Recommended for production applications due to its robustness, scalability, and advanced features.
# MariaDB: A community-developed fork of MySQL that is fully compatible with the MySQL backend.
# MySQL: A popular, fast, and reliable choice for many web applications.
# Oracle: An enterprise-grade database often used in large corporate environments.
# SQLite: The default database for Django (included with Python) and an excellent choice for development, testing,
# and small, low-traffic projects.


# What is django.shortcuts.render function?
# render() used to render template page by using  a single line of code , Instead of manually importing template loaders ,


# Key Arguments are:
# request (required): The incoming HTTP request object. This is essential for the
# template context processors to function correctly, such as adding user information to the context.
# template_name (required): The full name of the template file to be used (e.g., 'myapp/index.html').
# Django uses its template loader configuration to find the correct file.
# context (optional): A dictionary of data (key-value pairs) that will be available as variables
# within the template. The default is an empty dictionary.
# status (optional): The HTTP status code for the response, which defaults to 200 (OK).
# It is the primary method used in Django views for generating HTML responses from templates.


# Explain Q objects in Django ORM?
# # The Q object in Django is a powerful tool used to encapsulate SQL expressions,
# # The Q object allowing developers to build complex database queries that use  AND, OR, and NOT logical operators.
# # By default, keyword arguments in a filter() call are joined by AND conditions,
# # but Q objects provide the flexibility to override this behavior and create more intricate logic.


#                                             revision 6
# Signals in django
# Django signals are a built-in notification system that allows different parts of your application to communicate
# and perform actions, in response to specific events,
# without being tightly coupled.

# They operate on a publisher-subscriber pattern where a "sender" dispatches a signal, and "receivers" (functions or methods)
# listen for it and execute their logic.

# built in signals example:pre_save,post_save,pre_delete,post_delete,request_start,request_finish

#                       revision 7

# What are ‘sessions’
# In Django, sessions are a framework that allows you to store and retrieve user-specific data across multiple,
# otherwise stateless, HTTP requests. This enables a website to maintain the "state" of a visitor's interaction,
# such as remembering a logged-in user, tracking items in a shopping cart, or counting page visits.
# The session framework works by storing the actual data securely on the server side,
# while a unique session ID is stored as a cookie in the user's browser.
# First Request: When a user visits the site for the first time, Django's session middleware generates a unique, random session ID.
# Cookie Exchange: This ID is sent to the browser as a sessionid cookie.
# Subsequent Requests: On all future requests, the browser sends this cookie back to the server.
# Data Retrieval: Django uses the ID from the cookie to retrieve the corresponding session data from its storage backend (e.g., a database table called django_session).

# What is Django REST framework?
# Django REST framework (DRF) is a powerful and flexible toolkit for building Web APIs on top of the Django web framework.
# features: Serializers,Views and ViewSets :provides classes (like APIView and ModelViewSet),Authentication( (e.g., Token, Session, OAuth)) and Permissions,URL Routing,Filtering and Ordering

# What is serialization in Django
# the process of converting complex data types, such as Django model instances and querysets,
# into native Python data types (like dictionaries) that can then be easily rendered into content
# formats like JSON or XML for transmission over a network (e.g., in a web API response).
# features:  Data Translation,Data Validation,Handling Relationships,Code Reusability,


# revision 8

#
# What are routers in Django Rest Framework?
# In Django REST Framework (DRF), routers automatically generate URL patterns for ViewSet classes,
# simplifying the process of wiring HTTP methods (GET, POST, etc.) to the appropriate view logic.
# They eliminate the need for manually defining a URL pattern for every single API endpoint,
# resulting in cleaner and more maintainable code.
# SimpleRouter: The most basic router, which generates URL patterns
# for the standard set of list and detail actions (list, create, retrieve, update, partial_update, destroy).
# DefaultRouter: This router extends the SimpleRouter but additionally includes a default, browsable API root view
# that provides hyperlinks to all the list views, which is a great usability feature for developers.
# It's the generally recommended starting point.
What is CORS?
# CORS (Cross-Origin Resource Sharing) is a browser security feature that allows web pages from one domain (origin)
# to request resources (like APIs, fonts, images) from another domain,
# overcoming the default restriction called the Same-Origin Policy.
# It works by using special HTTP headers that servers send to tell browsers if it's safe to allow requests from different origins,
# enabling controlled access for powerful, integrated web applications while protecting against malicious data access.
What are viewsets?
# Django REST framework allows you to combine the logic for a set of related views in a single class, called a ViewSet.
# A ViewSet class is simply a type of class-based View, that does not provide any method handlers such as .get() or .post(),
# and instead provides actions such as .list() and .create().
#Key characteristics of ViewSets
Consolidated Logic: Groups related CRUD (Create, Read, Update, Delete) operations into one class.
Action-based: Uses methods like .list(), .create(), .retrieve(), .update(), .partial_update(), .destroy() instead of HTTP verbs.
Automatic Routing: Can be automatically wired to URLs using a Router (e.g., DefaultRouter), ensuring consistent URL conventions.
Rapid Development: Allows for faster API creation by minimizing boilerplate code.

#================ revision 9
#
# permission classes. what are they?
# Permissions are used to grant or deny access to different parts of the API by different users
    
#  built-in Permissions classes:
#                     AllowAny: Grants unrestricted access to everyone, regardless of whether they are authenticated or not.
#                      IsAuthenticated: Only allows access to users who have successfully logged in.
#                     IsAdminUser: Restricts access to users who have "staff" status (is_staff=True).
#                     IsAuthenticatedOrReadOnly: Allows unauthenticated users to use "safe" methods (GET, HEAD, OPTIONS) but requires authentication for any "unsafe" methods like POST, PUT, or DELETE.
#                     DjangoModelPermissions: Ties into Django's standard model-level permissions (add, change, delete).
#                     DjangoObjectPermissions: Provides granular access control at the individual object (database row) level.
#


