# Generated by Django 5.2.7 on 2025-11-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_ordered_date'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.product'),
        ),
    ]
