# Generated by Django 5.2.7 on 2025-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
